# runs tests and deploys to heroku if on master
name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: Install Client Dependencies
        run: npm ci
      - name: Run Client Tests
        run: npm test