# runs both client and server tests
name: test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Install Client Dependencies
        working-directory: ./client
        run: npm install
      - name: Run Client Tests
        working-directory: ./client
        run: npm test
      - name: Install Server Dependencies
        working-directory: ./server
        run: npm install
      - name: Run Server Tests
        working-directory: ./server
        run: npm test
